name: me5418-sim-only
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - pip:
      - numpy
      - scipy
      - matplotlib
      - tqdm
      - mujoco==3.3.6
      - gymnasium
      - imageio
      - imageio-ffmpeg
      - opencv-python