name: me5418-full
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  
  - pip:
      - numpy
      - scipy
      - matplotlib
      - tqdm
      - mujoco==3.3.6
      - gymnasium
      - gymnasium-robotics
      - stable-baselines3[extra]
      - imageio
      - imageio-ffmpeg
      - opencv-python
      - torch==2.8.0

