name: me5418-full
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - tensorboard=2.14.*
  - protobuf=3.20.*
  - pip:
      - mujoco==3.3.6
      - gymnasium
      - gymnasium-robotics
      - stable-baselines3[extra]
      - imageio
      - imageio-ffmpeg
      - opencv-python